image: hashicorp/terraform

pipelines:
  default:
      - step:
            name: Test
            script:
              - ls -la
              - chdir EC2
              - terraform init
              - terraform validate
              - terraform plan
  
