image: deepakdocker25/terraform-ansible:v7
pipelines:
  default:
      - step:
            name: Test
            script:
              - ls -la
              - chdir EC2
              - export AWS_ACCESS_KEY_ID=$ACCESS_KEY
              - export AWS_SECRET_ACCESS_KEY=$SECRET_KEY
              - pwd
              - whoami
              - terraform init
              - terraform validate
              - terraform plan
              - ansible --version
              #- ssh  -o StrictHostKeyChecking=no -i /root/testvm.pem ec2-user@13.235.50.132 "ls -la" 
              #- terraform apply --auto-approve
              - terraform destroy --auto-approve
  
/opt/atlassian/pipelines/agent/build/Ansible-Playbook/webapp/info.py