- hosts: Master
  tasks:
     - name: Fetch the file from the mwiapp01 to master
       run_once: yes
       fetch: src=/home/ec2-user/date.txt dest=/home/deepaksaini/ flat=yes
- hosts: Slave      
  tasks:
     - name: Copy the file from master to mwiapp02
       copy: src=/home/deepaksaini/date.txt dest=/home/ec2-user
       
